### ISSUE TITLE
Ajude a um inciante, please

### ISSUE THREAD

**Issue by gabrielfgularte** [JoamirS/project-django#1]
Oi Joamir, tudo bem? Dei uma olhada no teu projeto e acho que o problema é o seguinte:

O app `register` não está instalado no Django. Pra instalar um app, além de rodar o comando `./manage.py startapp NOME_DO_APP` vc precisa adicioná-lo na lista de `INSTALLED_APPS` no arquivo `settings.py` do seu projeto.

Exemplo:
```
INSTALLED_APPS = [
     'apps.register',
     'django.contrib.admin',
     'django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.messages',
     'django.contrib.staticfiles',

     # Meus apps
     'apps.register.apps.RegisterConfig',
]
```

Mas pra isso funcionar (já que vc quer separar os seus apps numa pasta chamada "apps"), vc precisa adicionar um arquivo vazio `__init__.py` na raiz dessa pasta ("apps"). Dessa forma vc transforma um diretório simples em um package "encontrável" pelo Python.

Veja se essas mudanças resolvem o problema e fala comigo novamente.

**Comment by JoamirS** [comment]
Olá, Gabriel. Bom dia.

Finalmente descobrir onde era o problema, eu não estava 'chamando' os módulos corretamente. 

Em project-django/apps/register/urls.py, estava escrito from . import views aí alterei para from register import views. E em project-django/apps/register/views.py estava from models import User ao invés de from register.models import User. 

E obrigado pela ajuda. Pedirei conselhos em breve ;)
